name: flutter_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: 3.10.0
  firebase_auth: 5.4.0
  cloud_firestore: 5.6.1
  firebase_storage: 12.4.0
  firebase_analytics: 11.4.0
  dash_chat: ^1.1.16
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true